version: '3.5'

services:
 
  modulo-afip-web:
    container_name: modulo-afip-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "250:80"
    volumes:
      # punto de entrada de la app symfony
      - ./public:/appdata/www/public
    depends_on:
      - modulo-afip-be
    networks:
      - modulo-afip-network

  modulo-afip-be:
    container_name: modulo-afip-be
    build:
      # Proxy configurado en el Dockerfile, no toma los archivos .env en el build
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_INI_DIR: /usr/local/etc/php
      ###> XDEBUG 3 ###
      # Use your client IP here
      # Linux: run "ip a | grep docker0"
      # Windows (with WSL2) and Mac: host.docker.internal
      # Las configuraciones se reflejan el archivo docker/php/xdebug.ini
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9005
      XDEBUG_ID_KEY: PHPSTORM
      PHP_IDE_CONFIG: serverName=Docker
      DEBUG: 1
    working_dir: /appdata/www
    volumes:
      - ./:/appdata/www
      - ./docker/php/php.ini:$PHP_INI_DIR/php.ini
      - ./docker/php/xdebug.ini:$PHP_INI_DIR/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - modulo-afip-db
    networks:
      - modulo-afip-network

  modulo-afip-db:
    container_name: modulo-afip-db
    build:
      context: ./docker/database
    ports:
      - "36001:3306"
    environment:
      MYSQL_DATABASE: 'modulo-afip'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - modulo-afip-db-data:/var/lib/mysql
      - './docker/database/mysqld.cnf:/etc/mysql/mysqld.cnf'
    networks:
      - modulo-afip-network

  modulo-afip-phpmyadmin:
    container_name: modulo-afip-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: modulo-afip-db
    depends_on:
      - modulo-afip-db
    networks:
      - modulo-afip-network


volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  modulo-afip-db-data:

networks:
  modulo-afip-network:
    external: true
